### ISSUE TITLE
Read Data from updated Slider speed

### ISSUE THREAD

**Issue by SharanjitV101** [wiedesign/GarbageCollectorRobot#32]
## User Story
The user shall obtain the speed corresponding to the slider position

## Acceptance Criteria
- [ ] Once the slider changes position, the values obtained based on the direction

### Subtasks

- [ ] Write the FE code
- [ ] Write the BE code
